### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Unable to launch triangular solve

### ISSUE THREAD

**Issue by arnon-1** [google-deepmind/ferminet#84]
I received the following error when trying to run the example script for H2.
I am using an AMD GPU with rocm version 6.0.3 (The LUMI supercomputer)
This is the output of `pip list | grep jax`.
the python version is 3.11.10

Thanks
```
jax                    0.4.31.dev20241012+eafb38ca8
jax-rocm60-pjrt        0.4.31
jax-rocm60-plugin      0.4.31
jaxlib                 0.4.31
jaxtyping              0.2.34
kfac-jax               0.0.6
```

```
1015 15:51:56.686672 22662944208704 train.py:900] Completed burn-in MCMC steps
I1015 15:51:59.581780 22662944208704 train.py:904] Initial energy: -1.1534 E_h
E1015 15:52:12.385106   26368 rocm_blas.cc:383] rocblas_strsm failed with: rocblas_status_memory_error
E1015 15:52:12.385187   26368 pjrt_stream_executor_client.cc:3067] Execution of replica 0 failed: INTERNAL: Unable to launch triangular solve
Traceback (most recent call last):
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/bin/ferminet", line 39, in <module>
    app.run(main)
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/bin/ferminet", line 35, in main
    train.train(cfg)
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/lib/python3.11/site-packages/ferminet/train.py", line 949, in train
    data, params, opt_state, loss, aux_data, pmove = step(
                                                     ^^^^^
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/lib/python3.11/site-packages/ferminet/train.py", line 351, in step
    new_params, new_state, stats = optimizer.step(
                                   ^^^^^^^^^^^^^^^
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1324, in step
    return self._step(params, state, rng, batch, func_state,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pfs/lustref1/flash/project_465001125/arn/setup/envs/jax/lib/python3.11/site-packages/kfac_jax/_src/utils/staging.py", line 248, in decorated
    outs = func(instance, *args)
           ^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Unable to launch triangular solve
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by arnon-1** [comment]
Ok, thanks. It indeed seems to be an installation issue.
