### ISSUE TITLE
`IndexError: list index out of range` in mcmc_step with JAX v0.4.36

### ISSUE THREAD

**Issue by annulen** [google-deepmind/ferminet#89]
When I've tried to verify if FermiNet is now operational after fix 9a1deec8222c1838c5aafb65830fc41372c48677, I've hit another error:

```
$ ferminet --config ferminet/configs/atom.py --config.system.atom Li --config.batch_size 256 --config.pretrain.iterations 100
<...snip...>
I1208 17:34:32.893374 139875094521664 train.py:584] No checkpoint found. Training new model.
Traceback (most recent call last):
  File "/home/ktokarev/venv/ferminet/bin/ferminet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 39, in <module>
    app.run(main)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 35, in main
    train.train(cfg)
  File "/mnt/storage/src/git/ferminet/ferminet/train.py", line 680, in train
    params, data.positions = pretrain.pretrain_hartree_fock(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage/src/git/ferminet/ferminet/pretrain.py", line 342, in pretrain_hartree_fock
    data, params, opt_state_pt, loss, pmove = pretrain_step(
                                              ^^^^^^^^^^^^^^
  File "/mnt/storage/src/git/ferminet/ferminet/pretrain.py", line 255, in pretrain_step
    data, pmove = mcmc_step(full_params, data, key, width=0.02)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage/src/git/ferminet/ferminet/mcmc.py", line 277, in mcmc_step
    new_data, key, _, num_accepts = lax.fori_loop(
                                    ^^^^^^^^^^^^^^
IndexError: list index out of range
```

This error disappears and pretraining starts fine if I roll back jax to v0.4.35, however, in the latter case a different error occurs after the end of the pretraining iterations:
```
$ ferminet --config ferminet/configs/atom.py --config.system.atom Li --config.batch_size 256 --config.pretrain.iterations 100
<...snip...?
I1208 17:41:02.053053 140690062513984 pretrain.py:344] Pretrain iter 00099: 0.000968613 0.914062
I1208 17:41:02.849053 140690062513984 tag_graph_matcher.py:1722] ==================================================
I1208 17:41:02.849577 140690062513984 tag_graph_matcher.py:1723] Graph parameter registrations:
{'envelope': [{'pi': 'Auto[tag_variant=scale_and_shift(1)|match_type=scale_only_broadcast_1]',
               'sigma': 'Auto[tag_variant=scale_and_shift(0)|match_type=scale_only_broadcast_1]'},
              {'pi': 'Auto[tag_variant=scale_and_shift(3)|match_type=scale_only_broadcast_1]',
               'sigma': 'Auto[tag_variant=scale_and_shift(2)|match_type=scale_only_broadcast_1]'}],
 'layers': {'input': {},
            'streams': [{'double': {'b': 'Auto[tag_variant=repeated_dense(1)|match_type=repeated_dense2_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(1)|match_type=repeated_dense2_with_bias]'},
                         'single': {'b': 'Auto[tag_variant=repeated_dense(0)|match_type=repeated_dense1_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(0)|match_type=repeated_dense1_with_bias]'}},
                        {'double': {'b': 'Auto[tag_variant=repeated_dense(3)|match_type=repeated_dense2_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(3)|match_type=repeated_dense2_with_bias]'},
                         'single': {'b': 'Auto[tag_variant=repeated_dense(2)|match_type=repeated_dense1_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(2)|match_type=repeated_dense1_with_bias]'}},
                        {'double': {'b': 'Auto[tag_variant=repeated_dense(5)|match_type=repeated_dense2_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(5)|match_type=repeated_dense2_with_bias]'},
                         'single': {'b': 'Auto[tag_variant=repeated_dense(4)|match_type=repeated_dense1_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(4)|match_type=repeated_dense1_with_bias]'}},
                        {'single': {'b': 'Auto[tag_variant=repeated_dense(6)|match_type=repeated_dense1_with_bias]',
                                    'w': 'Auto[tag_variant=repeated_dense(6)|match_type=repeated_dense1_with_bias]'}}]},
 'orbital': [{'w': 'Auto[tag_variant=repeated_dense(7)|match_type=repeated_dense1_no_bias]'},
             {'w': 'Auto[tag_variant=repeated_dense(8)|match_type=repeated_dense1_no_bias]'}]}
I1208 17:41:02.849617 140690062513984 tag_graph_matcher.py:1729] ==================================================
Traceback (most recent call last):
  File "/home/ktokarev/venv/ferminet/bin/ferminet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 39, in <module>
    app.run(main)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 35, in main
    train.train(cfg)
  File "/mnt/storage/src/git/ferminet/ferminet/train.py", line 852, in train
    opt_state = optimizer.init(params, subkeys, data)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1031, in init
    return self._init(params, rng, batch, func_state)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/staging.py", line 297, in decorated
    outs = func(instance, *args, **kwargs)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 999, in _init
    estimator_state=self.estimator.init(
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 342, in wrapped
    return method(instance, *args, **kwargs)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/curvature_estimator/block_diagonal.py", line 390, in init
    self.finalize(func_args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 315, in finalize
    self._finalize(*args, **kwargs)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/curvature_estimator/block_diagonal.py", line 375, in _finalize
    self._jaxpr = self._jaxpr_extractor(func_args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 466, in get_processed_jaxpr
    closed_jaxpr, _ = retrieve(func_args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 432, in retrieve
    processed_jaxpr = ProcessedJaxpr.make_from_func(
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 321, in make_from_func
    func = tgm.auto_register_tags(
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 2067, in auto_register_tags
    graph = make_jax_graph(
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 355, in make_jax_graph
    closed_jaxpr, out_shapes = jax.make_jaxpr(func, return_shape=True)(*func_args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1682, in value_func
    out, _ = value_and_grad_func(*args, **kwargs)
  File "/mnt/storage/src/git/ferminet/ferminet/loss.py", line 267, in total_energy_jvp
    psi_primal, psi_tangent = jax.jvp(batch_network, primals, tangents)
  File "/mnt/storage/src/git/ferminet/ferminet/train.py", line 525, in <lambda>
    logabs_network = lambda *args, **kwargs: signed_network(*args, **kwargs)[1]
  File "/mnt/storage/src/git/ferminet/ferminet/networks.py", line 1507, in apply
    orbitals = orbitals_apply(params, pos, spins, atoms, charges)
  File "/mnt/storage/src/git/ferminet/ferminet/networks.py", line 1172, in apply
    ae, ee, r_ae, r_ee = construct_input_features(pos, atoms, ndim=options.ndim)
  File "/mnt/storage/src/git/ferminet/ferminet/networks.py", line 477, in construct_input_features
    jnp.linalg.norm(ee + jnp.eye(n)[..., None], axis=-1) * (1.0 - jnp.eye(n)))
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 1050, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 646, in _getitem
    return lax_numpy._rewriting_take(self, item)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 11411, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 11452, in _gather
    return expand_dims(y, indexer.newaxis_dims)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py", line 2521, in expand_dims
    return lax.expand_dims(a, axis)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: _broadcast_in_dim_staging_rule() got an unexpected keyword argument 'sharding'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ktokarev/venv/ferminet/bin/ferminet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 39, in <module>
    app.run(main)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/mnt/storage/src/git/ferminet/bin/ferminet", line 35, in main
    train.train(cfg)
  File "/mnt/storage/src/git/ferminet/ferminet/train.py", line 852, in train
    opt_state = optimizer.init(params, subkeys, data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1031, in init
    return self._init(params, rng, batch, func_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/staging.py", line 297, in decorated
    outs = func(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 999, in _init
    estimator_state=self.estimator.init(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 342, in wrapped
    return method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/curvature_estimator/block_diagonal.py", line 390, in init
    self.finalize(func_args)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 315, in finalize
    self._finalize(*args, **kwargs)
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/curvature_estimator/block_diagonal.py", line 375, in _finalize
    self._jaxpr = self._jaxpr_extractor(func_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 466, in get_processed_jaxpr
    closed_jaxpr, _ = retrieve(func_args)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 432, in retrieve
    processed_jaxpr = ProcessedJaxpr.make_from_func(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tracer.py", line 328, in make_from_func
    typed_jaxpr = jax.make_jaxpr(func)(*func_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ktokarev/venv/ferminet/lib/python3.11/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 1696, in __call__
    flat_output = self._flat_func(*flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _broadcast_in_dim_staging_rule() got an unexpected keyword argument 'sharding'
```

**Comment by annulen** [comment]
Side note: wouldn't it be more productive to pin down certain dependencies (e.g., all stuff related to jax and kfac) to the versions which are know to work, and update them deliberately when certain feature is required, or when person doing such update has the time to verify that the new set of dependencies actually works when installing everything from scratch? I guess it would save a lot of time for everyone: no need to guess working revisions, no need to fight a fallback of unexpected updates in 3rd party code in the middle of other things.

**Comment by dibbla** [comment]
The same as #88 
Do you have any workaround at this point? 👀

**Comment by jsspencer** [comment]
> Side note: wouldn't it be more productive to pin down certain dependencies (e.g., all stuff related to jax and kfac) to the versions which are know to work, and update them deliberately when certain feature is required, or when person doing such update has the time to verify that the new set of dependencies actually works when installing everything from scratch? I guess it would save a lot of time for everyone: no need to guess working revisions, no need to fight a fallback of unexpected updates in 3rd party code in the middle of other things.

folx and kfac-jax use JAX internal APIs and so HEAD of this repository typically tracks HEAD of those and jax. This matches what we use in our own work. [Note that folx doesn't have any releases yet.]
I will take a look at pinning versions when I get time, but the ecosystem moves quickly that this has caused problems when we've had pinned versions in the past.

**Comment by jsspencer** [comment]
This is now fixed -- ensure you are using jax 0.4.37 or chex 0.1.88 (or both). Sorry for the breakage.

**Comment by annulen** [comment]
Thanks!

I wonder if it would be helpful to set up nightly CI builds for `ferminet` like it's done e.g. in `chex`: https://github.com/google-deepmind/chex/blob/master/.github/workflows/ci.yml#L9. But it would require keeping CI green, otherwise it would be useless. If you are interested I can submit PR for that.

**Comment by jsspencer** [comment]
I already have a change for fixing the github CI, which should be pushed soon.

[We also have internal CI which is always green, but that is testing against HEAD of the various dependencies]
